declare module '*.css';
declare module '@/components/ui/button';
declare module '@/components/ui/input';
declare module '@/components/ui/label'
declare module '@/components/ui/alert';
declare module '@/lib/api'
declare module '@/lib/auth';
declare module 'lucide-react';
declare module 'react';
declare module 'next';
declare module '@/components/ui/card'
declare module '@/components/ui/select'
declare module '@/components/ui/textarea'
declare module '@/components/ui/tabs'
declare module '@/components/ui/dialog'
declare module '@/components/ui/checkbox'
declare module '@/components/ui/navbar'
declare module '@/components/ui/sidebar'
declare module '@/components/ui/avatar'
declare module '@/components/ui/dropdown-menu'
declare module '@/components/ui/badge'
declare module '@/components/ui/progress'
declare module '@/components/ui/skeleton'
declare module '@/components/ui/scroll-area'
declare module '@/components/ui/popover'
declare module '@/components/ui/tooltip'
declare module '@/components/ui/radio-group'
declare module '@/components/ui/pagination'
declare module '@/components/ui/calendar'
declare module '@/components/ui/breadcrumbs'
declare module '@/components/game/particle-background'
declare module '@/components/game/pixel-button'
declare module '@/components/game/pixel-input'
declare module '@/components/game/logo'
declare module '@/lib/game-context'
declare module '@/components/particle-background'
declare module '@/components/pixel-button'
declare module '@/components/pixel-input'
declare module '@/components/logo'
declare module '@/lib/game-context'
declare module "TypewriterText"
declare module "framer-motion"
declare module "next/navigation"
declare module "next/link"
declare module "@/components/sidebar"
