// Comprehensive lessons data with 200+ lessons across all modules

export type LessonType = "reading" | "interactive" | "challenge" | "quiz" | "project"
export type Difficulty = "beginner" | "intermediate" | "advanced"

export interface Lesson {
  id: string
  title: string
  duration: string
  completed: boolean
  type: LessonType
  description: string
  content?: LessonContent
}

export interface LessonContent {
  overview: string
  codeExample?: string
  keyConcepts: string[]
  proTips: string[]
  relatedTopics: string[]
  externalLinks: { title: string; url: string }[]
  interactiveExample?: {
    html: string
    css: string
    description: string
  }
}

export interface LearningModule {
  id: string
  title: string
  description: string
  color: string
  difficulty: Difficulty
  topics: string[]
  lessons: Lesson[]
}

// Internet Basics Module - 25 Lessons
const internetBasicsLessons: Lesson[] = [
  {
    id: "ib-1",
    title: "What is the Internet?",
    duration: "5 min",
    completed: false,
    type: "reading",
    description: "Introduction to the global network",
  },
  {
    id: "ib-2",
    title: "History of the Internet",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "From ARPANET to modern web",
  },
  {
    id: "ib-3",
    title: "How Data Travels",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Packets, routing, and transmission",
  },
  {
    id: "ib-4",
    title: "IP Addresses Explained",
    duration: "7 min",
    completed: false,
    type: "reading",
    description: "IPv4, IPv6, and addressing",
  },
  {
    id: "ib-5",
    title: "DNS: Internet's Phone Book",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "Domain name resolution",
  },
  {
    id: "ib-6",
    title: "HTTP Protocol Basics",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Request-response cycle",
  },
  {
    id: "ib-7",
    title: "HTTPS and Security",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "SSL/TLS encryption",
  },
  {
    id: "ib-8",
    title: "Web Browsers Deep Dive",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "How browsers render pages",
  },
  {
    id: "ib-9",
    title: "Client-Server Model",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Understanding web architecture",
  },
  {
    id: "ib-10",
    title: "TCP/IP Protocol Suite",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Networking fundamentals",
  },
  {
    id: "ib-11",
    title: "Quiz: Network Basics",
    duration: "10 min",
    completed: false,
    type: "quiz",
    description: "Test your knowledge",
  },
  {
    id: "ib-12",
    title: "URLs and URIs",
    duration: "6 min",
    completed: false,
    type: "reading",
    description: "Web address anatomy",
  },
  {
    id: "ib-13",
    title: "HTTP Methods",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "GET, POST, PUT, DELETE",
  },
  {
    id: "ib-14",
    title: "HTTP Status Codes",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Understanding response codes",
  },
  {
    id: "ib-15",
    title: "Cookies and Sessions",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "State management on the web",
  },
  {
    id: "ib-16",
    title: "Web Hosting Basics",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Servers and deployment",
  },
  {
    id: "ib-17",
    title: "CDNs Explained",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Content delivery networks",
  },
  {
    id: "ib-18",
    title: "APIs Introduction",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Application programming interfaces",
  },
  {
    id: "ib-19",
    title: "REST API Basics",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "RESTful architecture",
  },
  {
    id: "ib-20",
    title: "WebSockets Overview",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Real-time communication",
  },
  {
    id: "ib-21",
    title: "Browser DevTools",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Network tab and debugging",
  },
  {
    id: "ib-22",
    title: "Web Security Basics",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Common vulnerabilities",
  },
  {
    id: "ib-23",
    title: "CORS Explained",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Cross-origin resource sharing",
  },
  {
    id: "ib-24",
    title: "Quiz: Advanced Networking",
    duration: "15 min",
    completed: false,
    type: "quiz",
    description: "Test advanced concepts",
  },
  {
    id: "ib-25",
    title: "Challenge: Debug Network Issues",
    duration: "20 min",
    completed: false,
    type: "challenge",
    description: "Practical troubleshooting",
  },
]

// HTML Mastery Module - 40 Lessons
const htmlMasteryLessons: Lesson[] = [
  {
    id: "html-1",
    title: "Introduction to HTML",
    duration: "5 min",
    completed: false,
    type: "reading",
    description: "What is HTML and why it matters",
  },
  {
    id: "html-2",
    title: "HTML Document Structure",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "DOCTYPE, html, head, body",
  },
  {
    id: "html-3",
    title: "Head Element Deep Dive",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Meta tags, title, links",
  },
  {
    id: "html-4",
    title: "Text Elements",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "Headings, paragraphs, spans",
  },
  {
    id: "html-5",
    title: "Text Formatting",
    duration: "6 min",
    completed: false,
    type: "reading",
    description: "Bold, italic, emphasis",
  },
  {
    id: "html-6",
    title: "Lists in HTML",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Ordered, unordered, definition",
  },
  {
    id: "html-7",
    title: "Links and Navigation",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Anchor tags and attributes",
  },
  {
    id: "html-8",
    title: "Images in HTML",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "img tag and optimization",
  },
  {
    id: "html-9",
    title: "Quiz: HTML Basics",
    duration: "10 min",
    completed: false,
    type: "quiz",
    description: "Test your knowledge",
  },
  {
    id: "html-10",
    title: "HTML5 Semantic Elements",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "header, nav, main, footer",
  },
  {
    id: "html-11",
    title: "Article and Section",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "Content organization",
  },
  {
    id: "html-12",
    title: "Figure and Figcaption",
    duration: "6 min",
    completed: false,
    type: "reading",
    description: "Media with captions",
  },
  {
    id: "html-13",
    title: "Tables Fundamentals",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "table, tr, td, th",
  },
  {
    id: "html-14",
    title: "Advanced Tables",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "colspan, rowspan, styling",
  },
  {
    id: "html-15",
    title: "Forms Introduction",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Form element basics",
  },
  {
    id: "html-16",
    title: "Input Types Part 1",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Text, email, password",
  },
  {
    id: "html-17",
    title: "Input Types Part 2",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Number, date, color",
  },
  {
    id: "html-18",
    title: "Textarea and Select",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Multi-line and dropdowns",
  },
  {
    id: "html-19",
    title: "Form Validation",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Required, patterns, constraints",
  },
  {
    id: "html-20",
    title: "Challenge: Build a Form",
    duration: "25 min",
    completed: false,
    type: "challenge",
    description: "Complete contact form",
  },
  {
    id: "html-21",
    title: "Audio Element",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "Adding sound to pages",
  },
  {
    id: "html-22",
    title: "Video Element",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Embedding video content",
  },
  {
    id: "html-23",
    title: "iframes",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Embedding external content",
  },
  {
    id: "html-24",
    title: "Canvas Basics",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Drawing graphics",
  },
  {
    id: "html-25",
    title: "SVG Introduction",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Scalable vector graphics",
  },
  {
    id: "html-26",
    title: "Quiz: HTML5 Features",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test advanced HTML",
  },
  {
    id: "html-27",
    title: "Accessibility Basics",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "WCAG guidelines intro",
  },
  {
    id: "html-28",
    title: "ARIA Attributes",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Accessible rich internet apps",
  },
  {
    id: "html-29",
    title: "Keyboard Navigation",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Focus and tab order",
  },
  {
    id: "html-30",
    title: "Screen Readers",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Testing accessibility",
  },
  {
    id: "html-31",
    title: "SEO Basics",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Search engine optimization",
  },
  {
    id: "html-32",
    title: "Meta Tags for SEO",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Open Graph, Twitter cards",
  },
  {
    id: "html-33",
    title: "Structured Data",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Schema.org markup",
  },
  {
    id: "html-34",
    title: "HTML Best Practices",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Clean and maintainable code",
  },
  {
    id: "html-35",
    title: "HTML Validation",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "W3C validator",
  },
  {
    id: "html-36",
    title: "Template Element",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Reusable HTML templates",
  },
  {
    id: "html-37",
    title: "Slot Element",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Web components basics",
  },
  {
    id: "html-38",
    title: "Quiz: Accessibility",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test a11y knowledge",
  },
  {
    id: "html-39",
    title: "Project: Portfolio Structure",
    duration: "30 min",
    completed: false,
    type: "project",
    description: "Build portfolio HTML",
  },
  {
    id: "html-40",
    title: "Challenge: Semantic Page",
    duration: "25 min",
    completed: false,
    type: "challenge",
    description: "Full semantic markup",
  },
]

// CSS Styling Module - 50 Lessons
const cssStylingLessons: Lesson[] = [
  {
    id: "css-1",
    title: "Introduction to CSS",
    duration: "5 min",
    completed: false,
    type: "reading",
    description: "What is CSS and its purpose",
  },
  {
    id: "css-2",
    title: "CSS Syntax",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "Selectors and declarations",
  },
  {
    id: "css-3",
    title: "Adding CSS to HTML",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Inline, internal, external",
  },
  {
    id: "css-4",
    title: "Basic Selectors",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Element, class, ID",
  },
  {
    id: "css-5",
    title: "Combinator Selectors",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Descendant, child, sibling",
  },
  {
    id: "css-6",
    title: "Pseudo-classes",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "hover, focus, nth-child",
  },
  {
    id: "css-7",
    title: "Pseudo-elements",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "before, after, first-line",
  },
  {
    id: "css-8",
    title: "Specificity",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Cascade and inheritance",
  },
  {
    id: "css-9",
    title: "Quiz: CSS Selectors",
    duration: "10 min",
    completed: false,
    type: "quiz",
    description: "Test selector knowledge",
  },
  {
    id: "css-10",
    title: "Colors in CSS",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Hex, RGB, HSL",
  },
  {
    id: "css-11",
    title: "Typography Basics",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "font-family, size, weight",
  },
  {
    id: "css-12",
    title: "Text Properties",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "alignment, decoration, spacing",
  },
  {
    id: "css-13",
    title: "Web Fonts",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Google Fonts, @font-face",
  },
  {
    id: "css-14",
    title: "Box Model",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "margin, padding, border",
  },
  {
    id: "css-15",
    title: "Box Sizing",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "content-box vs border-box",
  },
  {
    id: "css-16",
    title: "Display Property",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "block, inline, inline-block",
  },
  {
    id: "css-17",
    title: "Positioning Basics",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "static, relative, absolute",
  },
  {
    id: "css-18",
    title: "Fixed and Sticky",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Advanced positioning",
  },
  {
    id: "css-19",
    title: "Z-Index and Stacking",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Layer management",
  },
  {
    id: "css-20",
    title: "Challenge: Card Component",
    duration: "20 min",
    completed: false,
    type: "challenge",
    description: "Style a card",
  },
  {
    id: "css-21",
    title: "Flexbox Introduction",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Flexible box layout",
  },
  {
    id: "css-22",
    title: "Flex Container",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "display flex, direction",
  },
  {
    id: "css-23",
    title: "Flex Items",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "grow, shrink, basis",
  },
  {
    id: "css-24",
    title: "Flex Alignment",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "justify, align, gap",
  },
  {
    id: "css-25",
    title: "Flexbox Patterns",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Common layouts",
  },
  {
    id: "css-26",
    title: "Quiz: Flexbox",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test flexbox knowledge",
  },
  {
    id: "css-27",
    title: "Grid Introduction",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "CSS Grid layout",
  },
  {
    id: "css-28",
    title: "Grid Container",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "columns, rows, template",
  },
  {
    id: "css-29",
    title: "Grid Items",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "spanning and placement",
  },
  {
    id: "css-30",
    title: "Grid Areas",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Named grid areas",
  },
  {
    id: "css-31",
    title: "Grid vs Flexbox",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "When to use each",
  },
  {
    id: "css-32",
    title: "Challenge: Grid Layout",
    duration: "25 min",
    completed: false,
    type: "challenge",
    description: "Build a grid page",
  },
  {
    id: "css-33",
    title: "Responsive Design Intro",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Mobile-first approach",
  },
  {
    id: "css-34",
    title: "Media Queries",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Breakpoints and queries",
  },
  {
    id: "css-35",
    title: "Responsive Units",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "em, rem, vh, vw",
  },
  {
    id: "css-36",
    title: "Responsive Images",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "srcset and sizes",
  },
  {
    id: "css-37",
    title: "Container Queries",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Modern responsive CSS",
  },
  {
    id: "css-38",
    title: "Quiz: Responsive",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test responsive knowledge",
  },
  {
    id: "css-39",
    title: "Transitions",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Smooth state changes",
  },
  {
    id: "css-40",
    title: "Transforms",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "rotate, scale, translate",
  },
  {
    id: "css-41",
    title: "Keyframe Animations",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Complex animations",
  },
  {
    id: "css-42",
    title: "Animation Properties",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "timing, delay, iteration",
  },
  {
    id: "css-43",
    title: "CSS Variables",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Custom properties",
  },
  {
    id: "css-44",
    title: "CSS Functions",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "calc, min, max, clamp",
  },
  {
    id: "css-45",
    title: "Filters and Effects",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "blur, brightness, shadows",
  },
  {
    id: "css-46",
    title: "Gradients",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "linear and radial",
  },
  {
    id: "css-47",
    title: "Modern CSS Features",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "has, where, is",
  },
  {
    id: "css-48",
    title: "CSS Best Practices",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Organization and naming",
  },
  {
    id: "css-49",
    title: "Project: Responsive Page",
    duration: "35 min",
    completed: false,
    type: "project",
    description: "Full responsive design",
  },
  {
    id: "css-50",
    title: "Challenge: Animate UI",
    duration: "30 min",
    completed: false,
    type: "challenge",
    description: "Animated interface",
  },
]

// JavaScript Core Module - 55 Lessons
const javascriptCoreLessons: Lesson[] = [
  {
    id: "js-1",
    title: "Introduction to JavaScript",
    duration: "5 min",
    completed: false,
    type: "reading",
    description: "What is JavaScript",
  },
  {
    id: "js-2",
    title: "JavaScript History",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Evolution of JS",
  },
  {
    id: "js-3",
    title: "Adding JS to HTML",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "Script tags and loading",
  },
  {
    id: "js-4",
    title: "Variables: var, let, const",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Variable declarations",
  },
  {
    id: "js-5",
    title: "Data Types",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Primitives and objects",
  },
  {
    id: "js-6",
    title: "Strings",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "String methods and templates",
  },
  {
    id: "js-7",
    title: "Numbers and Math",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Numeric operations",
  },
  {
    id: "js-8",
    title: "Booleans and Comparisons",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Logical operations",
  },
  {
    id: "js-9",
    title: "Quiz: JS Basics",
    duration: "10 min",
    completed: false,
    type: "quiz",
    description: "Test fundamentals",
  },
  {
    id: "js-10",
    title: "Arrays Fundamentals",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Creating and accessing",
  },
  {
    id: "js-11",
    title: "Array Methods Part 1",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "push, pop, slice",
  },
  {
    id: "js-12",
    title: "Array Methods Part 2",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "map, filter, reduce",
  },
  {
    id: "js-13",
    title: "Objects Fundamentals",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Creating and accessing",
  },
  {
    id: "js-14",
    title: "Object Methods",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "keys, values, entries",
  },
  {
    id: "js-15",
    title: "Challenge: Data Structures",
    duration: "20 min",
    completed: false,
    type: "challenge",
    description: "Work with arrays/objects",
  },
  {
    id: "js-16",
    title: "Functions Basics",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Declaration and expression",
  },
  {
    id: "js-17",
    title: "Arrow Functions",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Modern function syntax",
  },
  {
    id: "js-18",
    title: "Parameters and Arguments",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Default and rest params",
  },
  {
    id: "js-19",
    title: "Scope",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Global, function, block",
  },
  {
    id: "js-20",
    title: "Closures",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Understanding closures",
  },
  {
    id: "js-21",
    title: "Quiz: Functions",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test function knowledge",
  },
  {
    id: "js-22",
    title: "Conditionals",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "if, else, switch",
  },
  {
    id: "js-23",
    title: "Loops: for and while",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Iteration basics",
  },
  {
    id: "js-24",
    title: "Loop Methods",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "forEach, for...of, for...in",
  },
  {
    id: "js-25",
    title: "DOM Introduction",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Document Object Model",
  },
  {
    id: "js-26",
    title: "Selecting Elements",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "querySelector methods",
  },
  {
    id: "js-27",
    title: "Modifying Elements",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "innerHTML, textContent",
  },
  {
    id: "js-28",
    title: "Creating Elements",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "createElement, appendChild",
  },
  {
    id: "js-29",
    title: "Event Listeners",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "addEventListener",
  },
  {
    id: "js-30",
    title: "Event Object",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Event properties",
  },
  {
    id: "js-31",
    title: "Event Bubbling",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Propagation and delegation",
  },
  {
    id: "js-32",
    title: "Challenge: Interactive UI",
    duration: "25 min",
    completed: false,
    type: "challenge",
    description: "Build interactive page",
  },
  {
    id: "js-33",
    title: "Callbacks",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Async programming intro",
  },
  {
    id: "js-34",
    title: "Promises",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Promise basics",
  },
  {
    id: "js-35",
    title: "Promise Methods",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "all, race, allSettled",
  },
  {
    id: "js-36",
    title: "Async/Await",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Modern async syntax",
  },
  {
    id: "js-37",
    title: "Fetch API",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "HTTP requests",
  },
  {
    id: "js-38",
    title: "Error Handling",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "try, catch, finally",
  },
  {
    id: "js-39",
    title: "Quiz: Async JS",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test async knowledge",
  },
  {
    id: "js-40",
    title: "Local Storage",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Client-side storage",
  },
  {
    id: "js-41",
    title: "Session Storage",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Session data",
  },
  {
    id: "js-42",
    title: "JSON",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Parse and stringify",
  },
  {
    id: "js-43",
    title: "Destructuring",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Array and object destructuring",
  },
  {
    id: "js-44",
    title: "Spread Operator",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Spread and rest",
  },
  {
    id: "js-45",
    title: "Template Literals",
    duration: "8 min",
    completed: false,
    type: "interactive",
    description: "String interpolation",
  },
  {
    id: "js-46",
    title: "Modules",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "import and export",
  },
  {
    id: "js-47",
    title: "Classes",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "OOP in JavaScript",
  },
  {
    id: "js-48",
    title: "Inheritance",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "extends and super",
  },
  {
    id: "js-49",
    title: "this Keyword",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Context in JavaScript",
  },
  {
    id: "js-50",
    title: "Quiz: Advanced JS",
    duration: "15 min",
    completed: false,
    type: "quiz",
    description: "Test advanced concepts",
  },
  {
    id: "js-51",
    title: "Regular Expressions",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Pattern matching",
  },
  {
    id: "js-52",
    title: "Date and Time",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Date object",
  },
  {
    id: "js-53",
    title: "Set and Map",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Modern data structures",
  },
  {
    id: "js-54",
    title: "Project: Todo App",
    duration: "40 min",
    completed: false,
    type: "project",
    description: "Build a todo app",
  },
  {
    id: "js-55",
    title: "Challenge: API Integration",
    duration: "30 min",
    completed: false,
    type: "challenge",
    description: "Fetch and display data",
  },
]

// React Fundamentals Module - 45 Lessons
const reactFundamentalsLessons: Lesson[] = [
  {
    id: "react-1",
    title: "Introduction to React",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "What is React",
  },
  {
    id: "react-2",
    title: "Why React?",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Benefits of React",
  },
  {
    id: "react-3",
    title: "Setting Up React",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Create React App, Vite",
  },
  {
    id: "react-4",
    title: "JSX Basics",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "JavaScript XML syntax",
  },
  {
    id: "react-5",
    title: "Components Intro",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Functional components",
  },
  {
    id: "react-6",
    title: "Props Basics",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Passing data to components",
  },
  {
    id: "react-7",
    title: "Props Destructuring",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Clean prop handling",
  },
  {
    id: "react-8",
    title: "Children Props",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Component composition",
  },
  {
    id: "react-9",
    title: "Quiz: React Basics",
    duration: "10 min",
    completed: false,
    type: "quiz",
    description: "Test fundamentals",
  },
  {
    id: "react-10",
    title: "useState Hook",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Managing state",
  },
  {
    id: "react-11",
    title: "State Updates",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Updating state correctly",
  },
  {
    id: "react-12",
    title: "Multiple State Variables",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Complex state",
  },
  {
    id: "react-13",
    title: "Object State",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "State with objects",
  },
  {
    id: "react-14",
    title: "Array State",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "State with arrays",
  },
  {
    id: "react-15",
    title: "Challenge: Counter App",
    duration: "20 min",
    completed: false,
    type: "challenge",
    description: "Build a counter",
  },
  {
    id: "react-16",
    title: "Event Handling",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Handling events in React",
  },
  {
    id: "react-17",
    title: "Form Handling",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Controlled components",
  },
  {
    id: "react-18",
    title: "Conditional Rendering",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Rendering based on state",
  },
  {
    id: "react-19",
    title: "Lists and Keys",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Rendering lists",
  },
  {
    id: "react-20",
    title: "Quiz: State and Events",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test state knowledge",
  },
  {
    id: "react-21",
    title: "useEffect Hook",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Side effects",
  },
  {
    id: "react-22",
    title: "Effect Dependencies",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Dependency array",
  },
  {
    id: "react-23",
    title: "Effect Cleanup",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Cleanup functions",
  },
  {
    id: "react-24",
    title: "useRef Hook",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "References and DOM",
  },
  {
    id: "react-25",
    title: "useMemo Hook",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Memoizing values",
  },
  {
    id: "react-26",
    title: "useCallback Hook",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Memoizing functions",
  },
  {
    id: "react-27",
    title: "Challenge: Data Fetching",
    duration: "25 min",
    completed: false,
    type: "challenge",
    description: "Fetch data with useEffect",
  },
  {
    id: "react-28",
    title: "Context API",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Global state",
  },
  {
    id: "react-29",
    title: "useContext Hook",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Consuming context",
  },
  {
    id: "react-30",
    title: "Context Patterns",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Best practices",
  },
  {
    id: "react-31",
    title: "useReducer Hook",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Complex state logic",
  },
  {
    id: "react-32",
    title: "Quiz: Hooks",
    duration: "15 min",
    completed: false,
    type: "quiz",
    description: "Test hooks knowledge",
  },
  {
    id: "react-33",
    title: "Custom Hooks",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Creating custom hooks",
  },
  {
    id: "react-34",
    title: "React Router Basics",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Client-side routing",
  },
  {
    id: "react-35",
    title: "Route Parameters",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Dynamic routes",
  },
  {
    id: "react-36",
    title: "Nested Routes",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Route nesting",
  },
  {
    id: "react-37",
    title: "Navigation",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Link and useNavigate",
  },
  {
    id: "react-38",
    title: "Challenge: Multi-Page App",
    duration: "30 min",
    completed: false,
    type: "challenge",
    description: "Build with routing",
  },
  {
    id: "react-39",
    title: "Error Boundaries",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Handling errors",
  },
  {
    id: "react-40",
    title: "React Performance",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Optimization tips",
  },
  {
    id: "react-41",
    title: "React DevTools",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Debugging React",
  },
  {
    id: "react-42",
    title: "Testing Basics",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Testing components",
  },
  {
    id: "react-43",
    title: "Quiz: Advanced React",
    duration: "15 min",
    completed: false,
    type: "quiz",
    description: "Test advanced concepts",
  },
  {
    id: "react-44",
    title: "Project: Blog App",
    duration: "45 min",
    completed: false,
    type: "project",
    description: "Build a blog",
  },
  {
    id: "react-45",
    title: "Challenge: Full CRUD App",
    duration: "40 min",
    completed: false,
    type: "challenge",
    description: "Complete CRUD operations",
  },
]

// TypeScript Module - 30 Lessons
const typescriptLessons: Lesson[] = [
  {
    id: "ts-1",
    title: "Introduction to TypeScript",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "What is TypeScript",
  },
  {
    id: "ts-2",
    title: "Why TypeScript?",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Benefits of types",
  },
  {
    id: "ts-3",
    title: "Setting Up TypeScript",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Installation and config",
  },
  {
    id: "ts-4",
    title: "Basic Types",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "string, number, boolean",
  },
  {
    id: "ts-5",
    title: "Arrays and Tuples",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Typed arrays",
  },
  {
    id: "ts-6",
    title: "Objects and Interfaces",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Defining object shapes",
  },
  {
    id: "ts-7",
    title: "Type Aliases",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Custom type names",
  },
  {
    id: "ts-8",
    title: "Union Types",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Multiple possible types",
  },
  {
    id: "ts-9",
    title: "Quiz: Basic Types",
    duration: "10 min",
    completed: false,
    type: "quiz",
    description: "Test type basics",
  },
  {
    id: "ts-10",
    title: "Functions with Types",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Typed parameters and returns",
  },
  {
    id: "ts-11",
    title: "Optional Parameters",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Optional and default",
  },
  {
    id: "ts-12",
    title: "Function Overloads",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Multiple signatures",
  },
  {
    id: "ts-13",
    title: "Generics Introduction",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Generic types",
  },
  {
    id: "ts-14",
    title: "Generic Functions",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Flexible functions",
  },
  {
    id: "ts-15",
    title: "Generic Constraints",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Constraining generics",
  },
  {
    id: "ts-16",
    title: "Challenge: Typed Utils",
    duration: "20 min",
    completed: false,
    type: "challenge",
    description: "Build typed utilities",
  },
  {
    id: "ts-17",
    title: "Enums",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Enumerated types",
  },
  {
    id: "ts-18",
    title: "Literal Types",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Exact value types",
  },
  {
    id: "ts-19",
    title: "Type Guards",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Narrowing types",
  },
  {
    id: "ts-20",
    title: "Type Assertions",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "as keyword",
  },
  {
    id: "ts-21",
    title: "Quiz: Advanced Types",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test advanced types",
  },
  {
    id: "ts-22",
    title: "Classes in TypeScript",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Typed classes",
  },
  {
    id: "ts-23",
    title: "Access Modifiers",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "public, private, protected",
  },
  {
    id: "ts-24",
    title: "Abstract Classes",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Abstract types",
  },
  {
    id: "ts-25",
    title: "Utility Types",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Partial, Required, Pick",
  },
  {
    id: "ts-26",
    title: "Mapped Types",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Type transformations",
  },
  {
    id: "ts-27",
    title: "Conditional Types",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Type conditionals",
  },
  {
    id: "ts-28",
    title: "TypeScript with React",
    duration: "20 min",
    completed: false,
    type: "interactive",
    description: "React + TypeScript",
  },
  {
    id: "ts-29",
    title: "Project: Typed React App",
    duration: "35 min",
    completed: false,
    type: "project",
    description: "Build typed app",
  },
  {
    id: "ts-30",
    title: "Challenge: Type System",
    duration: "25 min",
    completed: false,
    type: "challenge",
    description: "Complex type challenge",
  },
]

// Next.js Module - 25 Lessons
const nextjsLessons: Lesson[] = [
  {
    id: "next-1",
    title: "Introduction to Next.js",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "What is Next.js",
  },
  {
    id: "next-2",
    title: "Why Next.js?",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Benefits of Next.js",
  },
  {
    id: "next-3",
    title: "Creating a Next.js App",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Project setup",
  },
  {
    id: "next-4",
    title: "App Router Basics",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "File-based routing",
  },
  {
    id: "next-5",
    title: "Pages and Layouts",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Page structure",
  },
  {
    id: "next-6",
    title: "Dynamic Routes",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Dynamic segments",
  },
  {
    id: "next-7",
    title: "Route Groups",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Organizing routes",
  },
  {
    id: "next-8",
    title: "Quiz: Routing",
    duration: "10 min",
    completed: false,
    type: "quiz",
    description: "Test routing knowledge",
  },
  {
    id: "next-9",
    title: "Server Components",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "RSC basics",
  },
  {
    id: "next-10",
    title: "Client Components",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "use client directive",
  },
  {
    id: "next-11",
    title: "Data Fetching",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Fetching in components",
  },
  {
    id: "next-12",
    title: "Server Actions",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Form handling",
  },
  {
    id: "next-13",
    title: "Loading States",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "loading.tsx",
  },
  {
    id: "next-14",
    title: "Error Handling",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "error.tsx",
  },
  {
    id: "next-15",
    title: "Challenge: Blog with Next.js",
    duration: "30 min",
    completed: false,
    type: "challenge",
    description: "Build a blog",
  },
  {
    id: "next-16",
    title: "Image Optimization",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "next/image",
  },
  {
    id: "next-17",
    title: "Font Optimization",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "next/font",
  },
  {
    id: "next-18",
    title: "Metadata API",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "SEO with metadata",
  },
  {
    id: "next-19",
    title: "Middleware",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Request middleware",
  },
  {
    id: "next-20",
    title: "API Routes",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Route handlers",
  },
  {
    id: "next-21",
    title: "Quiz: Advanced Next.js",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test advanced concepts",
  },
  {
    id: "next-22",
    title: "Static Generation",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "SSG basics",
  },
  {
    id: "next-23",
    title: "Incremental Static Regen",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "ISR patterns",
  },
  {
    id: "next-24",
    title: "Project: E-commerce",
    duration: "45 min",
    completed: false,
    type: "project",
    description: "Build e-commerce",
  },
  {
    id: "next-25",
    title: "Challenge: Full Stack App",
    duration: "40 min",
    completed: false,
    type: "challenge",
    description: "Complete app",
  },
]

// Git & GitHub Module - 20 Lessons
const gitLessons: Lesson[] = [
  {
    id: "git-1",
    title: "Introduction to Git",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Version control basics",
  },
  {
    id: "git-2",
    title: "Installing Git",
    duration: "5 min",
    completed: false,
    type: "reading",
    description: "Setup and configuration",
  },
  {
    id: "git-3",
    title: "Git Basics",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "init, add, commit",
  },
  {
    id: "git-4",
    title: "Git Status and Log",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Viewing history",
  },
  {
    id: "git-5",
    title: "Branching Basics",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Creating branches",
  },
  {
    id: "git-6",
    title: "Merging Branches",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "Combining work",
  },
  {
    id: "git-7",
    title: "Resolving Conflicts",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Merge conflicts",
  },
  {
    id: "git-8",
    title: "Quiz: Git Basics",
    duration: "10 min",
    completed: false,
    type: "quiz",
    description: "Test git knowledge",
  },
  {
    id: "git-9",
    title: "Remote Repositories",
    duration: "12 min",
    completed: false,
    type: "interactive",
    description: "push, pull, fetch",
  },
  {
    id: "git-10",
    title: "GitHub Introduction",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "GitHub platform",
  },
  {
    id: "git-11",
    title: "Pull Requests",
    duration: "15 min",
    completed: false,
    type: "interactive",
    description: "Code review workflow",
  },
  {
    id: "git-12",
    title: "GitHub Issues",
    duration: "10 min",
    completed: false,
    type: "reading",
    description: "Issue tracking",
  },
  {
    id: "git-13",
    title: "Git Rebase",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "Rebasing commits",
  },
  {
    id: "git-14",
    title: "Git Stash",
    duration: "10 min",
    completed: false,
    type: "interactive",
    description: "Temporary storage",
  },
  {
    id: "git-15",
    title: "Git Reset",
    duration: "12 min",
    completed: false,
    type: "reading",
    description: "Undoing changes",
  },
  {
    id: "git-16",
    title: "Git Tags",
    duration: "8 min",
    completed: false,
    type: "reading",
    description: "Version tagging",
  },
  {
    id: "git-17",
    title: "GitHub Actions Intro",
    duration: "15 min",
    completed: false,
    type: "reading",
    description: "CI/CD basics",
  },
  {
    id: "git-18",
    title: "Quiz: Advanced Git",
    duration: "12 min",
    completed: false,
    type: "quiz",
    description: "Test advanced git",
  },
  {
    id: "git-19",
    title: "Project: Collaboration",
    duration: "30 min",
    completed: false,
    type: "project",
    description: "Team workflow",
  },
  {
    id: "git-20",
    title: "Challenge: Open Source",
    duration: "25 min",
    completed: false,
    type: "challenge",
    description: "Contribute to OSS",
  },
]

// Export all modules with their lessons
export const LEARNING_MODULES: LearningModule[] = [
  {
    id: "internet-basics",
    title: "Internet Fundamentals",
    description: "Understand how the web works: protocols, DNS, HTTP, and more.",
    color: "#0074D9",
    difficulty: "beginner",
    topics: ["HTTP/HTTPS", "DNS", "IP Addresses", "TCP/IP", "Web Browsers", "APIs"],
    lessons: internetBasicsLessons,
  },
  {
    id: "html-mastery",
    title: "HTML Mastery",
    description: "Learn semantic HTML, accessibility, and document structure.",
    color: "#FF851B",
    difficulty: "beginner",
    topics: ["Semantic Elements", "Forms", "Tables", "Media", "Accessibility", "SEO"],
    lessons: htmlMasteryLessons,
  },
  {
    id: "css-styling",
    title: "CSS Styling",
    description: "Master layouts, animations, responsive design, and modern CSS.",
    color: "#B10DC9",
    difficulty: "intermediate",
    topics: ["Flexbox", "Grid", "Animations", "Variables", "Responsive Design", "Modern CSS"],
    lessons: cssStylingLessons,
  },
  {
    id: "javascript-core",
    title: "JavaScript Core",
    description: "Variables, functions, DOM manipulation, and async programming.",
    color: "#FFDC00",
    difficulty: "intermediate",
    topics: ["Variables", "Functions", "DOM", "Events", "Async/Await", "ES6+"],
    lessons: javascriptCoreLessons,
  },
  {
    id: "react-fundamentals",
    title: "React Fundamentals",
    description: "Components, hooks, state management, and React patterns.",
    color: "#61DAFB",
    difficulty: "advanced",
    topics: ["Components", "Hooks", "State", "Props", "Context", "Router"],
    lessons: reactFundamentalsLessons,
  },
  {
    id: "typescript",
    title: "TypeScript Essentials",
    description: "Type safety, interfaces, generics, and TypeScript with React.",
    color: "#3178C6",
    difficulty: "intermediate",
    topics: ["Types", "Interfaces", "Generics", "Classes", "Utility Types", "React+TS"],
    lessons: typescriptLessons,
  },
  {
    id: "nextjs",
    title: "Next.js Mastery",
    description: "Server components, routing, data fetching, and full-stack React.",
    color: "#000000",
    difficulty: "advanced",
    topics: ["App Router", "RSC", "Data Fetching", "API Routes", "SSG", "ISR"],
    lessons: nextjsLessons,
  },
  {
    id: "git-github",
    title: "Git & GitHub",
    description: "Version control, collaboration, and open source workflows.",
    color: "#F05032",
    difficulty: "beginner",
    topics: ["Git Basics", "Branching", "GitHub", "Pull Requests", "CI/CD", "Collaboration"],
    lessons: gitLessons,
  },
]

// Helper functions
export function getModuleById(id: string): LearningModule | undefined {
  return LEARNING_MODULES.find((m) => m.id === id)
}

export function getLessonById(moduleId: string, lessonId: string): Lesson | undefined {
  const module = getModuleById(moduleId)
  return module?.lessons.find((l) => l.id === lessonId)
}

export function getTotalLessons(): number {
  return LEARNING_MODULES.reduce((acc, m) => acc + m.lessons.length, 0)
}

export function getTotalCompletedLessons(): number {
  return LEARNING_MODULES.reduce((acc, m) => acc + m.lessons.filter((l) => l.completed).length, 0)
}

export function getModuleProgress(moduleId: string): number {
  const module = getModuleById(moduleId)
  if (!module) return 0
  const completed = module.lessons.filter((l) => l.completed).length
  return Math.round((completed / module.lessons.length) * 100)
}
